export var cards =[
    {name : "Cannon", rarity : "Common", elixir : 3, target : "Ground", type : "Building", range : 5.5, aoe : false},
    {name : "Goblin Hut", rarity : "Rare", elixir : 5, target : "Ground", type : "Building", range : -1, aoe : false},
    {name : "Mortar", rarity : "Common", elixir : 4, target : "Ground", type : "Building", range : 11.5, aoe : true},
    {name : "Inferno Tower", rarity : "Rare", elixir : 5, target : "Air and Ground", type : "Building", range : 6, aoe : false},
    {name : "Bomb Tower", rarity : "Rare", elixir : 4, target : "Ground", type : "Building", range : 6, aoe : true},
    {name : "Barbarian Hut", rarity : "Rare", elixir : 7, target : "Ground", type : "Building", range : -1, aoe : false},
    {name : "Tesla", rarity : "Common", elixir : 4, target : "Air and Ground", type : "Building", range : 5.5, aoe : false},
    {name : "Elixir Collector", rarity : "Rare", elixir : 6, target : "", type : "Building", range : -1, aoe : false},
    {name : "X-Bow", rarity : "Epic", elixir : 6, target : "Ground", type : "Building", range : 11.5, aoe : false},
    {name : "Tombstone", rarity : "Rare", elixir : 3, target : "Ground", type : "Building", range : -1, aoe : false},
    {name : "Furnace", rarity : "Rare", elixir : 4, target : "Ground", type : "Building", range : -1, aoe : false},
    {name : "Goblin Cage", rarity : "Rare", elixir : 4, target : "Ground", type : "Building", range : 5, aoe : false},
    {name : "Goblin Drill", rarity : "Epic", elixir : 4, target : "Ground", type : "Building", range : 0, aoe : false},
    {name : "Fireball", rarity : "Rare", elixir : 4, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Arrows", rarity : "Common", elixir : 3, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Rage", rarity : "Epic", elixir : 2, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Rocket", rarity : "Rare", elixir : 6, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Goblin Barrel", rarity : "Epic", elixir : 3, target : "Ground", type : "Spell", range : -1, aoe : false},
    {name : "Freeze", rarity : "Epic", elixir : 4, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Mirror", rarity : "Epic", elixir : 1, target : "", type : "Spell", range : -1, aoe : false},
    {name : "Lightning", rarity : "Epic", elixir : 6, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Zap", rarity : "Common", elixir : 2, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Poison", rarity : "Epic", elixir : 4, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Graveyard", rarity : "Legendary", elixir : 5, target : "Ground", type : "Spell", range : -1, aoe : true},
    {name : "The Log", rarity : "Legendary", elixir : 2, target : "Ground", type : "Spell", range : 10.1, aoe : false},
    {name : "Tornado", rarity : "Epic", elixir : 3, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Clone", rarity : "Epic", elixir : 3, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Earthquake", rarity : "Rare", elixir : 3, target : "Ground", type : "Spell", range : -1, aoe : true},
    {name : "Barbarian Barrel", rarity : "Epic", elixir : 2, target : "Ground", type : "Spell", range : -1, aoe : false},
    {name : "Heal Spirit", rarity : "Rare", elixir : 1, target : "Air and Ground", type : "Troop", range : 2.5, aoe : true},
    {name : "Giant Snowball", rarity : "Common", elixir : 2, target : "Air and Ground", type : "Spell", range : -1, aoe : true},
    {name : "Royal Delivery", rarity : "Common", elixir : 3, target : "Ground", type : "Spell", range : -1, aoe : true},
    {name : "", rarity : "", elixir : 1, target : "", type : "", range : 1, aoe : false},

    {name : "", rarity : "", elixir : 1, target : "", type : "", range : 1, aoe : false}


]
